language: java
jdk:
- openjdk7
env:
- TERM=dumb
after_success:
- "./gradlew jacocoTestReport coveralls"
6d41a78d23bac6bc151fd8a334ea17ed21f89494:
  secure: aggUwHyAwWf8Qc7zAWUsf+wolTCE5VkKllt5CvPelM7/10e3p6QaucJm7XxwM9lETOr4sEp3ZEWUGQwRed+z8Mpx24CAWgs36yG18DIneVSLCvFQf4qztL9CCXTWg0DVfMXs2Eww4hEUSg1GUkSCSLjsKg5eHljkkfzr5GYIQaM=
