language: java
jdk:
- openjdk7
env:
- TERM=dumb
after_success:
- "./gradlew jacocoTestReport coveralls"
before_deploy:
- "./gradlew buildrpm"
deploy:
  on:
    all_branches: true
  provider: bintray
  file: "dpl.cfg"
  user: "benjaminrclark"
  key: 
    secure: aggUwHyAwWf8Qc7zAWUsf+wolTCE5VkKllt5CvPelM7/10e3p6QaucJm7XxwM9lETOr4sEp3ZEWUGQwRed+z8Mpx24CAWgs36yG18DIneVSLCvFQf4qztL9CCXTWg0DVfMXs2Eww4hEUSg1GUkSCSLjsKg5eHljkkfzr5GYIQaM=
