language: java
jdk:
- openjdk7
env:
  matrix:
  - TERM=dumb
  global:
    secure: L8I8ZOAG28NE4du33ZJ5l/9StdYM1f3HXZTHMgQMrmACYrTotVN7LSvOJD7Yn5seYfgP1/EVCToxCQe+7qQINU4rmO6/WwWN/16Eq4njZ9/1xD+3t+n6beN1estYLgrQQ7KQCFXBmXU47Ufn+wjjN27t/VP/2RLtMbcpk30HdtY=
after_success:
- "./gradlew jacocoTestReport coveralls"
before_deploy:
- "./gradlew buildrpm"
deploy:
  on:
    all_branches: true
  provider: bintray
  file: dpl.cfg
  user: benjaminrclark
  key: "$BINTRAY_API_KEY"
addons:
  apt:
    packages:
    - ffmpeg 
    - imagemagick
