#!/bin/sh
#
# cate start / stop CATE server
#
# chkconfig:   - 85 15
# description: CATE Server
# processname: cate
# pidfile: /var/run/cate.pid
# config: /etc/sysconfig/cate


### BEGIN INIT INFO
# Provides: cate
# Required-Start: network
# Required-Stop: 
# Should-Start: 
# Should-Stop: 
# Default-Start: 
# Default-Stop: 
# Short-Description: CATE Server 
# Description: Creating a Taxonomic eScience Application Server     
### END INIT INFO

# Source function library.
. /etc/rc.d/init.d/functions

prog="cate"
pidfile="/var/run/${prog}.pid"
config="/etc/sysconfig/${prog}"
logfile="/var/log/${prog}.log"
jarfile="/var/lib/${prog}.jar"
lockfile="/var/lock/subsys/${prog}"

start() {
    nohup java -jar $jarfile --spring.config.location=file:$config /tmp 2>> /dev/null >> $logfile &
    echo $! > $pidfile	
    echo -n $"Starting $prog: "
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    if [ -f $pidfile ]; then
        pid=$(cat $pidfile);
        kill $pid;
        rm $pidfile
    fi
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?

