Media Processing
===========

The media processing pipeline in CATE is significantly different from the media processing pipeline in eMonocot. In eMonocot, image processing happens in-line with processing image records - so as an image record is processed in a chunk, the image files are downloaded, processed and saved. As the image 
processing involves various transformations (e.g. producing thumbnail and large images), plus extracting various types of embedded metadata (e.g. EXIF), all of which can fail under certain circumstances, this makes any jobs which process image records somewhat brittle and slow. Including processing the image file alongside processing the image record makes reporting errors somewhat complex too. In addition, the processing logic only relied on the modified date and a conditional GET for determining whether an image had changed or not, and unfortunatly this was not implemented by many of the servers we were retrieving images from. It will not work for uploaded media in any case. 

In CATE, we allow images to be uploaded to a server ad-hoc by users, and we can't afford to wait to respond to the user once a single record has been submitted, so processing the media file itself happens asynchronously (i.e. in the background, once the image record has been saved and a response returned to the submitting user). Consequently the processed media (which are displayed in the CATE website) may become available sometime after a media record has been saved. 

When a multimedia record is processed, it launches a media processing job. This job is queued up as a launch request like any other job, and processed once a batch processing thread becomes
available. The location of media file to be processed could be specified in two ways depending on how the media record was updated. If the media record was updated by a person as part of an iteractive edit using the CATE user interface and the media file was uploaded to a server and then stored in the shared, network accessible storage abstracted by the file transfer service, it will be given an upload url starting with "upload://". Such files are fetched to the batch processing node at the start of the multimedia processing pipeline by the file transfer service and stored temporarily on the batch node for the duration of the job.
Uploaded files are given random filenames and the multimedia records have the format http://${tenantname}/multimedia/original/${UUID}.${extension} to prevent collisions where multiple files are uploaded with 
the same name. If a multimedia record is being processed as part of a bulk processing batch process, the multimedia file may exist at the url which is the identifier of the multimedia record. In this case the identifier of the record is know and the multimedia file is fetched from the url and stored temporarily on the batch node for the duration of the job. There is an error condition where the identifier of the
multimedia record is not a URL or the URL does not return any content or returns a non OK response. This part of the pipeline is handled by the MultimediaFetchingProcessor, which delegates to the GetResourceClient or the FileTransferService, depending on the origin of the file. 

If the image file has been processed previously, then further processing is skipped if the image was originally uploaded and there is no new uploaded file available. If the file was originally fetched from the location pointed to by its identifier, the GetResourceClient will issue a conditional GET request and skip of the server responds with a 304 Not Modified status. Servers hosting content to be harvested by CATE should respond to conditional requests correctly to conditional requests to avoid the overhead of serving multimedia files unneccessarily. 

Once the file has been fetched, the MultimediaFetchingProcessor tries to determine whether the multimedia file has changed since it was last processed. In the case that the multimedia file has never been processed, it simply generates values which are used subsequently. It does this by comparing (a) a hash of the first 765 bytes of each file, (b) the size in bytes of each file (c) the height / width of the file (if the file is an image) or the duration of the audio (if the file is audio) or the height / width and duration of the video (if the file is video). If these values are the same, then the media file is deemed to be unchanged and is not processed further.

The final stage of the job involves writing the multimedia record back to the database, adding any metadata which might have been extracted from the media file itself. In addition 
